name: async_benchmark
description: A Dart package for running and analyzing benchmarks with support for isolated environments and performance tracking.
version: 1.0.0
repository: https://github.com/eneural-net/async_benchmark

environment:
  sdk: ^3.5.0

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.9
